Add NGINX role
eggshell/ansible-znc pull request #4
Opened 2017-01-20 23:29 UTC by mlangbehn

Added NGINX role which:
- Adds NGINX stable PPA
- Installs latest stable NGINX
- Configures NGINX as a reverse proxy

Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

2017-01-23 15:17 UTC, eggshell requested changes

2017-01-23 15:17 UTC, eggshell commented on roles/nginx/defaults/main.yml
> +nginx_dest_port: 8080
5000, unless we want to overwrite with an env config.

2017-01-23 15:22 UTC, mlangbehn commented on roles/nginx/defaults/main.yml
> +nginx_dest_port: 8080
8080 is a good default. I think we should change it in the env config.

2017-01-23 15:30 UTC, eggshell commented on roles/nginx/tasks/main.yml
> +    state: latest
Using 'latest` is generally a bad practice in ansible (though I understand passable in this case based on the ppa). Refer to #6.

2017-01-23 16:03 UTC, mlangbehn commented on roles/nginx/defaults/main.yml
> +nginx_dest_port: 8080
Since this repo is specifically for installing and configuring a ZNC host, I think you may be right. I'll switch it to 5000.

2017-01-23 22:32 UTC, eggshell requested changes

2017-01-23 22:32 UTC, eggshell commented on inventories/localhost
> +[nginx:children]
can you add this to `inventories/droplet` as well?

2017-01-23 22:32 UTC, eggshell commented on roles/nginx/tasks/main.yml
> +
Can we get a task to enable the NGINX service?

2017-01-23 22:39 UTC, mlangbehn commented on inventories/localhost
> +[nginx:children]
Already done.

2017-01-23 22:42 UTC, mlangbehn commented on roles/nginx/tasks/main.yml
> +
Good call...

2017-01-23 22:44 UTC, eggshell approved these changes

2017-01-23 22:45 UTC, eggshell commented
lgtm

2017-01-24 01:56 UTC, eggshell requested changes
Along with the inline comments, I'm getting a 502 when trying to visit the site I'm testing with. Probably need to adjust `reverse-proxy.conf`.

2017-01-24 01:56 UTC, eggshell commented on roles/nginx/tasks/main.yml
> +    status: started
`status:` should be `state:`

2017-01-24 01:56 UTC, eggshell commented on roles/nginx/defaults/main.yml
> +nginx_site_port: 80
We'll need a task to make sure the ports in this file are allowed in ufw.

2017-01-24 01:58 UTC, eggshell commented on roles/nginx/templates/reverse-proxy
> +server {
can we make the location of this file match the location it will be moving to? ex: `templates/etc/nginx/sites-available/reverse-proxy`

2017-01-24 01:58 UTC, eggshell commented on roles/nginx/tasks/main.yml
> +    src: reverse-proxy
see comment below about `src` filepath.

2017-01-24 17:11 UTC, mlangbehn commented on roles/nginx/tasks/main.yml
> +
This has been taken care of.

2017-01-24 17:11 UTC, mlangbehn commented on roles/nginx/defaults/main.yml
> +nginx_site_port: 80
This has been taken care of.

2017-01-26 16:11 UTC, eggshell approved these changes

2017-01-26 16:11 UTC, merged